### ISSUE TITLE
ALL_min_buy_volume ?

### ISSUE THREAD

**Issue by BaGRoS** [stevenshizzleh/pt_quick_sales#1]
In you readme You wrote
Q: Will this work with BTC?
A: Yes. You will need to update the below two properties in your PAIRS.properties.
	market = BTC
	ALL_max_trading_pairs = ???
but ALL_min_buy_volume is in ETH then should be changed. 2500 ETH ~ 135 BTC ?

**Comment by TomBos** [comment]
Volume is the amount of trades, has nothing to do with the value of a coin, AFAIK.

**Comment by BaGRoS** [comment]
Of course!
Wiki PT: "Tell the bot to only buy coins with a minimum volume of specified amount. Volume is measured in units of your base currency. If you are trading BTC, 500 = 500 BTC in 24 hour volume. If USDT, 500 = $500 (so you may need to increase this value according to volume levels on USDT on the exchange in question)."
Market ETH: ALL_min_buy_volume = 2500
2500 ETH
If somebody change market to BTC and leave this
ALL_min_buy_volume = 2500
then have 2500 BTC.
If somebody want change yours settings to BTC market then must make more changes.
Coins with volume 2500 ETH is a lot, but with volume 2500 BTC only few.

**Comment by stevenshizzleh** [comment]
I see what you're saying. Let me update the FAQ.

**Comment by TomBos** [comment]
I was so wrong...
